---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gitops-demo
  name: gitops-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-demo
  template:
    metadata:
      labels:
        app: gitops-demo
    spec:
      containers:
      - name: gitops-demo
        image: bibhas2/gitops-demo-webapp
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitops-demo
  name: gitops-demo-service
spec:
  ports:
  - name: app-ports
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: gitops-demo
  type: NodePort
