apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux
  namespace: flux-system
spec:
  interval: 15s
  ref:
    branch: main
  url: https://github.com/nchaithanyakoushi/flux
