apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux
  namespace: flux-system
spec:
  interval: 5m0s
  path: ../../
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux
  targetNamespace: default
